apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: log-receiver-api-sm
  labels:
    release: prom-stack
spec:
  selector:
    matchLabels:
      app: log-receiver-api-service
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
  namespaceSelector:
    matchNames:
      - default
