global:
  scrape_interval: 15s


scrape_configs:
  - job_name: "log-receiver-api"
    metrics_path: /metrics
    static_configs:
      - targets: ["log-receiver-api:3000"]

  - job_name: "parser"
    static_configs:
      - targets: ["log-parser:8000"]
