apiVersion: v1
kind: Service
metadata:
  name: log-receiver-api-service
  labels:
    app: log-receiver-api-service
spec:
  type: ClusterIP
  selector:
    app: log-receiver-api
  ports: 
    - name: http
      port: 3000
      targetPort: 3000
