apiVersion: v1
kind: Service
metadata:
  name: log-parser-service
  labels:
    app: log-parser
spec:
  type: ClusterIP
  selector:
    app: log-parser
  ports:
    - name: http
      port: 8000
      targetPort: 8000

