apiVersion: v1
data:
  alertmanager.yml: |
    route:
      receiver: log
      group_wait: 30s
      group_interval: 5m
      repeat_interval: 2h

    receivers:
      - name: log
        webhook_configs:
          - url: http://dozzle:8080/
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: alertmanager-config
