apiVersion: v1
data:
  alerts.yml: "groups:\n  - name: parser_alerts\n    rules:\n      - alert: ParserDown\n
    \       expr: up{job=\"parser\"} == 0\n        for: 2m\n        labels:\n          severity:
    critical\n        annotations:\n          summary: \"Parser container is down\"\n
    \         description: \"Unable to scrape log-parser for more than 2 minutes.\"\n\n
    \     - alert: ParserErrorRateHigh\n        expr: rate(parser_errors_total[5m])
    > 0.1\n        for: 1m\n        labels:\n          severity: warning\n        annotations:\n
    \         summary: \"High error rate for log-parser service\"\n          description:
    \" {{ $value }} errors in parser.\"\n\n      - alert: APIIsDown\n        expr:
    up{job=\"log-receiver-api\"} == 0\n        for: 1m\n        labels:\n          severity:
    critical\n        annotations: \n          summary: \"NodeJS API is down\"\n          description:
    \"Unable to scrape NodeJS API for more than 1 minute.\"\n"
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: prometheus-alerts
