apiVersion: v1
data:
  prometheus.yml: |+
    global:
      scrape_interval: 15s


    alerting:
      alertmanagers:
        - static_configs:
          - targets: ["alertmanager-service:9093"]

    rule_files:
      - alerts.yml

    scrape_configs:
      - job_name: "log-receiver-api"
        metrics_path: /metrics
        static_configs:
          - targets: ["log-receiver-api-service:3000"]

      - job_name: "parser"
        static_configs:
          - targets: ["log-parser-service:8000"]


kind: ConfigMap
metadata:
  creationTimestamp: null
  name: prometheus-config
