apiVersion: batch/v1
kind: CronJob
metadata:
  name: parser-cron
spec:
  schedule: "*/2 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: parser
              image: log-parser:latest
              imagePullPolicy: Never
              command: ["python", "logparsing_for_testing.py"]
              args: ["sample.log"]
          restartPolicy: Never
