name: CI Pipeline

on:
  push:
    branches: [main,dev]
  pull_request:

jobs:
  # Build Job
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Build all services
        run: docker-compose build

      - name: Start services
        run: docker-compose up -d

      - name: Wait for API to start
        run: sleep 5

      - name: Test API via cURL
        run: |
          curl -X POST http://localhost:3000/logs \
          -H "Content-Type: application/json" \
          -d '{"logs": [["Test log line"]]}'
     
      - name: Clean containers
        run: docker-compose down
