name: Frontend CI

on:
  push:
    branches:
      - main
      - frontend
  pull_request:
    branches:
      - main

jobs:
  test-react:
    name: Run React Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Run ESLint
        run: npm run lint

      - name: Run tests
        run: npm test -- --watchAll=false

      - name: Build project
        run: npm run build

