name: Integration CI

on:
  push:
    branches: [main, dev, staging]
    paths:
      - 'parser/**'
      - 'log-receiver-api/**'
      - 'docker-compose.yml'
  pull_request:
    branches: [main, dev, staging]

jobs:
  integration-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Build services
        run: docker compose -f docker-compose.yml build

      - name: Start services
        run: docker compose -f docker-compose.yml up -d

      - name: Wait for backend
        run: |
                for i in {1..10}; do
                        curl -sSf http://localhost:3000/health && break
                        echo "Waiting for backend..."
                        sleep 2
                done

      - name: Create test log
        run: echo "ERROR Integration test log" > parser/test.log

      - name: Run parser
        run: |
                docker compose -f docker-compose.yml run --rm log-parser python logparsing.py parser/test.log --once

      - name: Check backend logs
        run: |
                docker compose -f docker-compose.yml logs log-receiver-api | grep "Integration test log"

      - name: Tear down
        if: always()
        run: docker compose -f docker-compose.yml down

