name: Terraform CI 

on:
  push:
    branches: [main,dev,terraform-modules]
    paths:
      - 'terraform/**'
  pull_request:
    branches: [main,dev,staging,terraform-modules]
    paths:
      - 'terraform/**'

permissions: 
  id-token: write
  contents: read

jobs:
  terraform-check:
    name: Terraform check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::633359116457:role/OIDC-GitHub-LogParserForwarderRepo
          aws-region: eu-north-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2


      - name: Terraform Format
        working-directory: ./terraform/projectAWS
        run: |
                terraform fmt
                terraform fmt modules/ec2
                terraform fmt modules/s3
                terraform fmt modules/ebs
                terraform fmt modules/vpc
                terraform fmt -check
                terraform fmt -check modules/ec2
                terraform fmt -check modules/s3
                terraform fmt -check modules/ebs
                terraform fmt -check modules/vpc
      - name: Terraform Init
        working-directory: ./terraform/projectAWS
        run: terraform init

      - name: Terraform Validate
        working-directory: ./terraform/projectAWS
        run: terraform validate

      - name: Terraform plan
        working-directory: ./terraform/projectAWS
        run: terraform plan -var-file=./modules/environments/dev/main.tfvars

